# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'FTSDKDemo' do
 # Comment the next line if you don't want to use dynamic frameworks
  
  use_modular_headers!
  pod 'SnapKit', '~> 5.6.0'
  pod 'SDWebImage'
  pod 'MBProgressHUD', '~> 1.2.0'
  # RUM, Log ,Trace
  pod 'FTMobileSDK', '1.6.2-alpha.3'
  # Session Replay Configure
  pod 'FTMobileSDK/FTSessionReplay','1.6.2-alpha.3'

  pod 'Toast-Swift', '~> 5.0.1'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'OpenTelemetry-Swift-Protocol-Exporter-Http'
  pod 'OpenTelemetry-Swift-Sdk'
end

target 'FTSDKWidgetDemo' do
  use_modular_headers!
  # RUM, Log ,Trace in Extension
  pod 'FTMobileSDK/Extension', '1.6.2-alpha.3'
end
# Solve the issue of not finding the static library libarclite_iphonesimulator.a/libarclite_iphoneos.a
#post_install do |installer|
#   installer.generated_projects.each do |project|
#    project.targets.each do |target|
#        target.build_configurations.each do |config|
#            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '10.0'
#         end
#    end
#  end
#end
